### ISSUE TITLE
If B button is pressed first after power on the device restarts

### ISSUE THREAD

**Issue by llewmihs** [NUSTEM-UK/ConnectLib#26]
When the device is first powered an initial press of B to send the Happy Mood causes the device to reset.
To get around this you need to cycle through the moods and get back to Happy to send.

**Comment by jjsanderson** [comment]
I'm assuming this is due to one of performedMood, networkMood and instrinsicMood not being initialised properly. self->start_there.

**Comment by jjsanderson** [comment]
Bothers. myMood, extrinsicMood and performedMood are all initialised to moods[0].

**Comment by jjsanderson** [comment]
Aaaah, but those assignments are made before moods[] is populated in setup(). OK, that makes sense. Moving the assignments into setup()…
